# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2cf3e81d3913450fd56e9b991af323957d5adae4239aa088bdcbadbdf9d782e38b594756ee71cf1f7e7f83a31be923d1e473a919adba42e7c728acc56388f63

test:
  secret_key_base: cff812b631f25c5bfebcb20df63db4cd87e70036584726db88e51ce692ccf712e07eb304210af503a09de0f4c7b3da4914e0015a8a35ce9cf21dc9a7eab053ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
